#!/bin/bash
# Description: Gene family expansion and contraction analysis with error model
# Journal: G3: Genes, Genomes, Genetics (Genome Report)
# Software: CAFE5

# OrthoFinder 결과물에서 전처리된 유전자군 카운트 파일 지정
CAFE_INPUT="Orthogroups.GeneCount_formatted.tsv" 
TREE_FILE="mcmctree_calibrated.nwk"
CAFE_DIR="cafe5_results"

echo "=========================================================="
echo "Step 1: Generating the calibrated tree file (Newick format)"
echo "=========================================================="
# The following Newick tree was converted from the NEXUS-formatted 'FigTree.tre'
# generated by MCMCTREE, as CAFE5 strictly requires the Newick format.
cat <<EOF > $TREE_FILE
(((((Ctenopharyngodon_idella:0.432455,(((Gobio_gobio:0.212649,Pseudorasbora_parva:0.212649):0.137499,Phoxinus_phoxinus:0.350147):0.029525,Rhodeus_sinensis:0.379673):0.052782):0.185586,(Labeo_rohita:0.367904,Onychostoma_macrolepis:0.367904):0.250137):0.108318,Danio_rerio:0.726359):0.434252,Misgurnus_anguillicaudatus:1.160611):1.12693,(Gasterosteus_aculeatus:1.223465,Oryzias_latipes:1.223465):1.064076);
EOF

echo "=========================================================="
echo "Step 2: Run CAFE5 with Error Model (-e)"
echo "=========================================================="
# -e option implements the Viterbi algorithm to adjust for missing or falsely duplicated genes
cafe5 -i $CAFE_INPUT -t $TREE_FILE -e -o $CAFE_DIR -c 24

echo "=========================================================="
echo "CAFE5 analysis complete. Expanded/Contracted nodes saved in ${CAFE_DIR}/"
echo "=========================================================="
